"""M4 additive State Service facade, contracts and persistence."""

from .contracts import (
    M4AgentIdentity,
    M4CommandEnvelope,
    M4CommandType,
    M4QueryType,
    M4ReasonCode,
    M4StateMcpMethod,
    M4_STATE_MCP_METHOD_MATRIX,
    M4_QUERY_TYPES,
    M4_WRITE_COMMAND_TYPES,
    ModelBudgetRequest,
    ProviderCallStatus,
    ProviderUsageStatus,
    RuntimeConfigSpec,
    TrustedProviderUsageReceipt,
    TrustedRuntimeContext,
    derive_provider_usage_receipt_id,
    derive_usage_ledger_id,
    settlement_idempotency_key,
)
from .database import M4PostgresStateStore, M4StateTransaction
from .service import M4StateServiceFacade
from .validation import (
    load_m4_schema,
    m4_request_hash,
    validate_m4_command_envelope,
    validate_model_budget_reservation,
    validate_provider_usage_receipt,
    validate_runtime_config_snapshot,
    validate_state_mcp_call,
)

__all__ = (
    "M4AgentIdentity",
    "M4CommandEnvelope",
    "M4CommandType",
    "M4QueryType",
    "M4PostgresStateStore",
    "M4ReasonCode",
    "M4StateMcpMethod",
    "M4StateServiceFacade",
    "M4StateTransaction",
    "M4_STATE_MCP_METHOD_MATRIX",
    "M4_QUERY_TYPES",
    "M4_WRITE_COMMAND_TYPES",
    "ModelBudgetRequest",
    "ProviderCallStatus",
    "ProviderUsageStatus",
    "RuntimeConfigSpec",
    "TrustedProviderUsageReceipt",
    "TrustedRuntimeContext",
    "derive_provider_usage_receipt_id",
    "derive_usage_ledger_id",
    "settlement_idempotency_key",
    "load_m4_schema",
    "m4_request_hash",
    "validate_m4_command_envelope",
    "validate_model_budget_reservation",
    "validate_provider_usage_receipt",
    "validate_runtime_config_snapshot",
    "validate_state_mcp_call",
)
